name: Process Emails and Add to Calendar

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  process_emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client PyPDF2

      - name: Write credentials to file
        run: |
          echo "${{ secrets.CREDENTIALS_JSON }}" > /home/runner/work/credentials.json

      - name: Debug - Print credentials.json content
        run: |
          cat /home/runner/work/credentials.json

      - name: Run script
        run: python main.py
